batch_size: 128
custom_noise: false
dataset_name: cifar100
exp_id: exp_2021-12-03 12:09:50.374569
lc_n_epoch: -1
lr: 0.001
make_new_custom_noise: false
mo: false
n_epochs: 300
noise_mode: dependent
p: 0.4
seed: 123
sigma: 0
