batch_size: 128
custom_noise: false
dataset_name: cifar100
exp_id: exp_2021-12-03 14:51:11.441549
lc_n_epoch: 250
lr: 0.001
make_new_custom_noise: false
mo: true
n_epochs: 300
noise_mode: dependent
p: 0.4
seed: 123
sigma: 0.1
