batch_size: 128
custom_noise: true
dataset_name: cifar100
exp_id: exp_2021-11-29 15:14:24.277293
lc_n_epoch: -1
lr: 0.001
make_new_custom_noise: false
mo: false
n_epochs: 300
noise_mode: sym
p: 0.4
seed: 123
sigma: 0
