batch_size: 128
custom_noise: false
dataset_name: cifar10
exp_id: exp_2021-11-27 11:11:07.020347
lc_n_epoch: -1
lr: 0.001
make_new_custom_noise: false
mo: true
n_epochs: 300
noise_mode: dependent
p: 0.4
seed: 123
sigma: 0.5
