batch_size: 128
custom_noise: true
dataset_name: cifar10
exp_id: exp_2021-12-02 21:36:20.466696
lc_n_epoch: -1
lr: 0.001
make_new_custom_noise: true
mo: false
n_epochs: 300
noise_mode: asym
p: 0.4
seed: 123
sigma: 0.2
