batch_size: 128
custom_noise: false
dataset_name: cifar10
exp_id: exp_2021-11-26 11:18:36.051172
lc_n_epoch: 250
lr: 0.001
make_new_custom_noise: false
mo: true
n_epochs: 300
noise_mode: sym
p: 0.4
seed: 123
sigma: 1.0
