batch_size: 128
custom_noise: true
dataset_name: cifar10
exp_id: exp_2021-11-26 16:16:06.031597
lc_n_epoch: 250
lr: 0.001
make_new_custom_noise: false
mo: true
n_epochs: 300
noise_mode: asym
p: 0.4
seed: 123
sigma: 0.5
